[program:hotel-reverb]
process_name=%(program_name)s
command=php /home/osusnetw/back.osus.network/artisan reverb:start --host=127.0.0.1 --port=8080
autostart=true
autorestart=true
user=osusnetw
redirect_stderr=true
stdout_logfile=/home/osusnetw/back.osus.network/storage/logs/reverb.log
stopwaitsecs=10

[program:hotel-queue]
process_name=%(program_name)s
command=php /home/osusnetw/back.osus.network/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=osusnetw
redirect_stderr=true
stdout_logfile=/home/osusnetw/back.osus.network/storage/logs/queue.log
stopwaitsecs=10
